# run with `docker-compose up -d`
# to unmount volume and reinitialize schema/data, run with `docker-compose down -v`
version: '3.5'
services:
  example-app:
    build: 
      context: .
      dockerfile: local.Dockerfile
    restart: always
    env_file: 
      - local-properties.env
    ports:
      - 3000:3000
    command: ./scripts/build-local "example-app"
    healthcheck:
      test: ["CMD", "curl", "--silent", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/usr/local/go/src/example-module
      # Mount gCloud configuration
      - ~/.config/gcloud/:/root/.config/gcloud/
      # Mount dependencies
      - ~/go/src/github.com:/go/src/github.com
    networks:
      - example
networks:
  example:
    name: example
volumes:
  db_data:
